version: "3.8"
services:
  redis:
    image: "redis:alpine"

    command: redis-server

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - redis_net

# networking for the Redis container
networks:
  redis_net:
    driver: bridge
